#!/bin/bash

QUIVER="/home/$USER/.oh-my-zsh/custom/aliases/hero-arrows-alias.zsh"

ASCII=(
  "    (         "
  "     \        "
  "      )       "
  " >>-------->⚡"       
  "      )       "
  "     /        "
  "    (         "
)

TEXT=(
  ""
  "╦  ╦╔═╗╦ ╦╔╦╗  ┌─┐┬─┐┬─┐┌─┐┬ ┬"
  "║  ║║ ╦╠═╣ ║   ├─┤├┬┘├┬┘│ ││││"
  "╩═╝╩╚═╝╩ ╩ ╩   ┴ ┴┴└─┴└─└─┘└┴┘"
  "Magic Arrows that instantly link you directly anywhere!"
)
   
showSplash(){
  ART=(
    "\n${ASCII[0]} ${TEXT[0]}"
    "\n${ASCII[1]} ${TEXT[0]}"
    "\n${ASCII[2]} ${TEXT[1]}"
    "\n${ASCII[3]} ${TEXT[2]}"
    "\n${ASCII[4]} ${TEXT[3]}"
    "\n${ASCII[5]} ${TEXT[0]}"
    "\n${ASCII[6]} ${TEXT[4]}"
  )
  echo -e "${ART[@]}\n"
  INSCRIPTION='"Name me and I will travel directly here when fired"'

  echo "  🏹 ${USER} picks up a new arrow with an inscription written...

  >>>>>>>___________________________________\`-._ 
  >>>>>>>          Arrow of Light           /.-' ${PWD}

  ${INSCRIPTION}
  "
}

wizardComment(){
  export HOL_NPC=wizard
  export HEY_LISTEN="Great shot!";
}

createNewArrow(){
  read -e -p "🏹 $USER thinks to themselves, 'What do I name this magical arrow [i.e: a.parent.child]?': a." LABEL
  touch $QUIVER
  ARROW=(
    "cd $PWD;" 
    "ls -la;"
    "source hero-light-arrow . $LABEL"
  )
  echo "alias a.$LABEL='${ARROW[@]}'" >> $QUIVER
  echo "💯 Nice!"
  echo "👕 $USER Added the light arrow >>>----a.$LABEL----->  to their Quiver 🏹!"
  export HEY_LISTEN="\"Use the arrow's name, a.$LABEL, to go directly to $PWD!\""
}

lightArrow(){
  case $1 in
    ".")
      echo "🏹 *Whooosh* >>>----a.$2-----> 🎯"
      wizardComment
      ;;

    *)
      showSplash
      createNewArrow
      # Reload zsh to enable newly created alias
      zsh 
      ;;
  esac
}

lightArrow $@