#!/bin/bash

local FLOORS=(
  ../
  ../..
  ../../..
  ../../../..
  ../../../../.. 
  ../../../../../.. 
  ../../../../../../.. 
  ../../../../../../../.. 
  ../../../../../../../../.. 
)

ASCII=(
  "  8 8          ,o.  "
  " d8o8azzzzzzzzd   b "
  "               \`o'  "
  "                    " 
)

TEXT=(
  "╔╦╗╔═╗╔═╗╦╔═╗  ┬┌─┌─┐┬ ┬"
  "║║║╠═╣║ ╦║║    ├┴┐├┤ └┬┘"
  "╩ ╩╩ ╩╚═╝╩╚═╝  ┴ ┴└─┘ ┴ "
  ""
)

showSplash(){
  ART=(
    "\n${ASCII[1]} ${TEXT[1]}"
    "\n${ASCII[2]} ${TEXT[2]}"
    "\n${ASCII[3]} ${TEXT[3]}"
    "\n${ASCII[4]} ${TEXT[4]}"
  )
  echo -e "${ART[@]}"
}

magicKey(){
  KEY=${1:=1}
  echo -e "👕️ $USER takes the magic key and turns it $KEY times... 🗝🚪 \n"
  export HEY_LISTEN="Type '-' to go back to: ${PWD}"
  cd  ${FLOORS[$KEY]}
}

showSplash
magicKey $@