#!/bin/bash

PAD="/home/$USER/hero-magic-crayon"

ASCII=(
  "  ________________________________________     "
  " /\______________________________________/\`-.  "
  "<()>N___________________________________<    ##"
  " \/______________________________________\,-'  "
)

TEXT=(
  ""
  "╔╦╗╔═╗╔═╗╦╔═╗  ┌┬┐┌─┐┬─┐┬┌─┌─┐┬─┐"
  "║║║╠═╣║ ╦║║    │││├─┤├┬┘├┴┐├┤ ├┬┘"
  "╩ ╩╩ ╩╚═╝╩╚═╝  ┴ ┴┴ ┴┴└─┴ ┴└─┘┴└─"
)

showSplash(){
  ART=(
    "\n${ASCII[1]} ${TEXT[1]}"
    "\n${ASCII[2]} ${TEXT[2]}"
    "\n${ASCII[3]} ${TEXT[3]}"
    "\n${ASCII[4]} ${TEXT[4]}"
  )
  echo -e "${ART[@]}"
}

removeLastMark(){
  sed -i '$d' $PAD
}

saveMark(){
  if [ "$1" != "" ]; then
    touch "$PAD"
    echo "$@" >> "$PAD"
    echo "️️👕 $USER Wrote: 🖍️ $@!"
    export HEY_LISTEN="Use n- to remove last mark."
  fi
}

magicMarker(){
  echo "🖍️ MAGIC MARKER @️ ${PAD}"

  case $1 in
    "-d") removeLastMark ;;
    *) saveMark $@ ;;
  esac


  cat "$PAD"

}

showSplash
magicMarker $@