#!/bin/bash

ASCII=(
  "    (         "
  "     \        "
  "      )       "
  " >>-------->🔥"       
  "      )       "
  "     /        "
  "    (         "
)

TEXT=(
  ""
  "╔═╗╦╦═╗╔═╗  ┌─┐┬─┐┬─┐┌─┐┬ ┬┌─┐"
  "╠╣ ║╠╦╝║╣   ├─┤├┬┘├┬┘│ ││││└─┐"
  "╚  ╩╩╚═╚═╝  ┴ ┴┴└─┴└─└─┘└┴┘└─┘"
  "Burn through your downloads one arrow at a time!"
)

showSplash(){
  ART=(
    "\n${ASCII[0]} ${TEXT[0]}"
    "\n${ASCII[1]} ${TEXT[0]}"
    "\n${ASCII[2]} ${TEXT[1]}"
    "\n${ASCII[3]} ${TEXT[2]}"
    "\n${ASCII[4]} ${TEXT[3]}"
    "\n${ASCII[5]} ${TEXT[0]}"
    "\n${ASCII[6]} ${TEXT[4]}"
  )
  echo -e "${ART[@]}\n"
}

function fireArrows(){
  cd "/home/$USER/Downloads/"
  pwd
  for FILE in *; do
    ARROWS=$( ls -p /home/$USER/Downloads/ | grep -v / | wc -l )
    echo "🔥🏹 $ARROWS $FILE";
    rm -i "$FILE"
  done
}

showSplash
fireArrows